name: Functional Testing

on:
  push:
    branches: [ main ]
    paths:
      - 'server/crates/nc_test_client/**'
      - '.github/workflows/nc_test_client.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/crates/nc_test_client/**'
      - '.github/workflows/nc_test_client.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: server/target
          key: ${{ runner.os }}-cargo-build-target-ft-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --tests --manifest-path ./server/crates/nc_test_client/Cargo.toml --verbose
      - name: Run tests
        run: cargo test --manifest-path ./server/crates/nc_test_client/Cargo.toml --verbose
