name: Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --manifest-path ./server/Cargo.toml --verbose
    - name: Run tests
      run: cargo test --manifest-path ./server/Cargo.toml --verbose
