name: Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: server/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --tests --manifest-path ./server/Cargo.toml --verbose
      - name: Run unit tests
        run: cargo test --lib --manifest-path ./server/Cargo.toml --verbose

  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/game-server
          tag_with_sha: true
          tag_with_ref: true
          path: ./server

  ft:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    services:
      game-server:
        image: docker.pkg.github.com/jjmark15/noughts-and-crosses/game-server:main
        ports:
          - 3030:3030
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: server/target
          key: ${{ runner.os }}-cargo-build-target-ft-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --test testing --manifest-path ./server/Cargo.toml --verbose
      - name: Run functional tests
        run: cargo test --test testing --manifest-path ./server/Cargo.toml --verbose
        env:
          GAME_SERVER_HOST: localhost:3030
