name: Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: server/target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --tests --manifest-path ./server/Cargo.toml --verbose
      - name: Run unit tests
        run: cargo test --lib --manifest-path ./server/Cargo.toml --verbose

  ft:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache cargo build
        uses: actions/cache@v2
        with:
          path: server/target
          key: ${{ runner.os }}-cargo-build-target-ft-${{ hashFiles('**/Cargo.lock') }}
      - name: Build
        run: cargo build --test testing --manifest-path ./server/Cargo.toml --verbose
      - name: Bring up services
        run: docker-compose up -d
      - name: Run functional tests
        run: cargo test --test testing --manifest-path ./server/Cargo.toml --verbose
